---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: build-test
  image: golang
  commands:
    - make build
    - make test
  when:
    event:
    - pull_request
    - tag
    - push
    ref:
    - refs/heads/custom
    - refs/tags/*

- name: copy-binary
  image: busybox
  commands:
    - mkdir -p .build/linux-amd64
    - cp json_exporter .build/linux-amd64/
  when:
    event:
    - tag
    - push
    ref:
    - refs/heads/custom
    - refs/tags/*

- name: docker-push
  image: plugins/docker
  settings:
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    registry: docker.io
    repo: ciscocx/json_exporter
  when:
    event:
    - tag
    - push
    ref:
    - refs/heads/custom
    - refs/tags/*

---
kind: signature
hmac: ef5802aa77009e213424a31db9aa1f62402bfbf95cd992859830203c8bfe3c64

...
